INPUT_DIR: "data/scenarios"
FILES:
  - "BEL_Antwerp-30_3_T-1.xml"
  - "BEL_Brussels-37_1_T-1.xml"
  - "ESP_Vigo-89_1_T-1.xml"
OUTPUT_DIR: "data/output"
BUILD_DIR: "build"
TARGET_SPEED: 10.0
SAVE_PLOT: true
PLANNER:
  TICK_T: 0.1
  ROAD_WIDTH: 7.0
  N_W_SAMPLE: 5
  LOWEST_SPEED: 6.0
  HIGHEST_SPEED: 12.0
  N_S_SAMPLE: 5
  MIN_T: 3.0
  MAX_T: 5.0
  N_T_SAMPLE: 5
  CHECK_OBSTACLE: true
  CHECK_BOUNDARY: true
VEHICLE:
  LENGTH: 4.5
  WIDTH: 1.8
  MAX_SPEED: 15.0
  MAX_ACCEL: 4.0
  MAX_CURVATURE: 0.35
